/**
 * ⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️
 * BE CAREFUL WHEN EDITING THIS FILE
 * This file contains constant arrays used across the application.
 * Any changes here may affect multiple parts of the system.
 * Ensure to review dependencies before making modifications.
 */

// 1.
export const roles = ['admin', 'employer', 'candidate', 'guest'] as const;

// 2.
export const maritalStatus = [
  'single',
  'married',
  'divorced',
  'widowed',
] as const;

// 3.
export const genders = ['male', 'female', 'other'] as const;

// 4.
export const nationalities = [
  'afghan',
  'albanian',
  'algerian',
  'american',
  'andorran',
  'angolan',
  'antiguans',
  'argentinean',
  'armenian',
  'australian',
  'austrian',
  'azerbaijani',
  'bahamian',
  'bahraini',
  'bangladeshi',
  'barbadian',
  'barbudans',
  'batswana',
  'belarusian',
  'belgian',
  'belizean',
  'beninese',
  'bhutanese',
  'bolivian',
  'bosnian',
  'brazilian',
  'british',
  'bruneian',
  'bulgarian',
  'burkinabe',
  'burmese',
  'burundian',
  'cambodian',
  'cameroonian',
  'canadian',
  'cape verdean',
  'central african',
  'chadian',
  'chilean',
  'chinese',
  'colombian',
  'comoran',
  'congolese',
  'costa rican',
  'croatian',
  'cuban',
  'cypriot',
  'czech',
  'danish',
  'djibouti',
  'dominican',
  'dutch',
  'east timorese',
  'ecuadorean',
  'egyptian',
  'emirian',
  'equatorial guinean',
  'eritrean',
  'estonian',
  'ethiopian',
  'fijian',
  'filipino',
  'finnish',
  'french',
  'gabonese',
  'gambian',
  'georgian',
  'german',
  'ghanaian',
  'greek',
  'grenadian',
  'guatemalan',
  'guineabissauan',
  'guinean',
  'guyanese',
  'haitian',
  'herzegovinian',
  'honduran',
  'hungarian',
  'ikiribati',
  'icelander',
  'indian',
  'indonesian',
  'iranian',
  'iraqi',
  'irish',
  'israeli',
  'italian',
  'ivorian',
  'jamaican',
  'japanese',
  'jordanian',
  'kazakhstani',
  'kenyan',
  'kittian and nevisian',
  'kuwaiti',
  'kyrgyz',
  'laotian',
  'latvian',
  'lebanese',
  'liberian',
  'libyan',
  'liechtensteiner',
  'lithuanian',
  'luxembourger',
  'macedonian',
  'malagasy',
  'malawian',
  'malaysian',
  'maldivian',
  'malian',
  'maltese',
  'marshallese',
  'mauritanian',
  'mauritian',
  'mexican',
  'micronesian',
  'moldovan',
  'monacan',
  'mongolian',
  'moroccan',
  'mosotho',
  'motswana',
  'mozambican',
  'namibian',
  'nauruan',
  'nepalese',
  'new zealander',
  'nivanuatu',
  'nicaraguan',
  'nigerian',
  'nigerien',
  'north korean',
  'northern irish',
  'norwegian',
  'omani',
  'pakistani',
  'palauan',
  'panamanian',
  'papua new guinean',
  'paraguayan',
  'peruvian',
  'polish',
  'portuguese',
  'qatari',
  'romanian',
  'russian',
  'rwandan',
  'saint lucian',
  'salvadoran',
  'samoan',
  'san marinese',
  'sao tomean',
  'saudi',
  'scottish',
  'senegalese',
  'serbian',
  'seychellois',
  'sierra leonean',
  'singaporean',
  'slovakian',
  'slovenian',
  'solomon islander',
  'somali',
  'south african',
  'south korean',
  'spanish',
  'sri lankan',
  'sudanese',
  'surinamer',
  'swazi',
  'swedish',
  'swiss',
  'syrian',
  'taiwanese',
  'tajik',
  'tanzanian',
  'thai',
  'togolese',
  'tongan',
  'trinidadian or tobagonian',
  'tunisian',
  'turkish',
  'tuvaluan',
  'ugandan',
  'ukrainian',
  'uruguayan',
  'uzbekistani',
  'venezuelan',
  'vietnamese',
  'welsh',
  'yemenite',
  'zambian',
  'zimbabwean',
] as const;

// 5.
export const currencies = [
  'AED',
  'AFN',
  'ALL',
  'AMD',
  'ANG',
  'AOA',
  'ARS',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CAD',
  'CDF',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'EUR',
  'FJD',
  'FKP',
  'GBP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IQD',
  'IRR',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SGD',
  'SHP',
  'SLE',
  'SLL',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SVC',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XCG',
  'XDR',
  'XOF',
  'XPF',
  'XSU',
  'YER',
  'ZAR',
  'ZMW',
  'ZWG',
  'ZWL',
] as const;

// 6.
export const salaryPeriods = ['yearly', 'monthly', 'hourly'] as const;

// 7.
export const qualifications = [
  'none',
  'high_school',
  'associate_degree',
  'bachelor_degree',
  'master_degree',
  'doctorate_degree',
  'professional_certification',
  'other',
] as const;

// 8.
export const jobTags = [
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'react', label: 'React' },
  { value: 'node.js', label: 'Node.js' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'next.js', label: 'Next.js' },
  { value: 'angular', label: 'Angular' },
  { value: 'vue.js', label: 'Vue.js' },
  { value: 'swift', label: 'Swift' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'dart', label: 'Dart' },
  { value: 'react native', label: 'React Native' },
  { value: 'sql', label: 'SQL' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'aws lambda', label: 'AWS Lambda' },
  { value: 'azure functions', label: 'Azure Functions' },
  { value: 'netlify', label: 'Netlify' },
  { value: 'vercel', label: 'Vercel' },
  { value: 'render', label: 'Render' },
  { value: 'docker', label: 'Docker' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'shopify', label: 'Shopify' },
  { value: 'magento', label: 'Magento' },
  { value: 'drupal', label: 'Drupal' },
  { value: 'joomla', label: 'Joomla' },
  { value: 'spring boot', label: 'Spring Boot' },
  { value: 'express.js', label: 'Express.js' },
  { value: 'gatsby', label: 'Gatsby' },
  { value: 'python', label: 'Python' },
  { value: 'django', label: 'Django' },
  { value: 'flask', label: 'Flask' },
  { value: 'ruby on rails', label: 'Ruby on Rails' },
  { value: 'java', label: 'Java' },
  { value: 'spring', label: 'Spring' },
  { value: 'c', label: 'C' },
  { value: 'c++', label: 'C++' },
  { value: 'c#', label: 'C#' },
  { value: '.net', label: '.NET' },
  { value: 'php', label: 'PHP' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
  { value: 'aws', label: 'AWS' },
  { value: 'azure', label: 'Azure' },
  { value: 'gcp', label: 'GCP' },
] as const;

// 9.
export const jobLevels = [
  'internship',
  'entry_level',
  'junior_level',
  'associate',
  'mid_senior_level',
  'senior_level',
  'lead',
  'manager',
  'director',
  'executive',
] as const;

// 10.
export const jobTypes = ['on_site', 'remote', 'hybrid'] as const;

// 11.
export const workTypes = [
  'full_time',
  'part_time',
  'contract',
  'temporary',
  'volunteer',
  'internship',
  'other',
] as const;

// 12.
export const applicationStatus = [
  'pending',
  'under_review',
  'interview_scheduled',
  'offered',
  'rejected',
  'hired',
] as const;

// 13.
export const interviewStatuses = [
  'scheduled',
  'completed',
  'canceled',
  'rescheduled',
] as const;

// 14.
export const jobBenefits = [
  'health_insurance',
  'dental_insurance',
  'vision_insurance',
  'retirement_plan',
  'paid_time_off',
  'flexible_schedule',
  'remote_work_options',
  'professional_development',
  'wellness_programs',
  'commuter_benefits',
  'childcare_assistance',
  'employee_assistance_programs',
  'stock_options',
  'performance_bonus',
  'tuition_reimbursement',
  'life_insurance',
  'disability_insurance',
  'learning_budget',
  'gym_membership',
  'team_building_activities',
  'free_snacks_and_beverages',
] as const;

// 15.
// Legal/structural classification
export const organizationTypes = [
  'public company',
  'private company',
  'educational institution',
  'government agency',
  'sole proprietorship',
  'partnership',
  'corporation',
  'non-profit',
] as const;

// 16.
// Industry/domain classification
export const industries = [
  'development',
  'business',
  'finance & accounting',
  'it & software',
  'office productivity',
  'personal development',
  'design & creative',
  'marketing',
  'photography & video',
  'health & fitness',
  'music',
  'teaching & academics',
  'retail',
  'manufacturing',
  'hospitality & tourism',
  'construction',
  'real estate',
  'legal',
  'transportation & logistics',
] as const;

// 17.
export const locales = [
  'af',
  'ar',
  'ar-DZ',
  'ar-EG',
  'ar-MA',
  'ar-SA',
  'ar-TN',
  'az',
  'be',
  'be-tarask',
  'bg',
  'bn',
  'bs',
  'ca',
  'ckb',
  'cs',
  'cy',
  'da',
  'de',
  'de-AT',
  'el',
  'en-AU',
  'en-CA',
  'en-GB',
  'en-IE',
  'en-IN',
  'en-NZ',
  'en-US',
  'en-ZA',
  'eo',
  'es',
  'et',
  'eu',
  'fa-IR',
  'fi',
  'fr',
  'fr-CA',
  'fr-CH',
  'fy',
  'gd',
  'gl',
  'gu',
  'he',
  'hi',
  'hr',
  'ht',
  'hu',
  'hy',
  'id',
  'is',
  'it',
  'it-CH',
  'ja',
  'ja-Hira',
  'ka',
  'kk',
  'km',
  'kn',
  'ko',
  'lb',
  'lt',
  'lv',
  'mk',
  'mn',
  'ms',
  'mt',
  'nb',
  'nl',
  'nl-BE',
  'nn',
  'oc',
  'pl',
  'pt',
  'pt-BR',
  'ro',
  'ru',
  'se',
  'sk',
  'sl',
  'sq',
  'sr',
  'sr-Latn',
  'sv',
  'ta',
  'te',
  'th',
  'tr',
  'ug',
  'uk',
  'uz',
  'uz-Cyrl',
  'vi',
  'zh-CN',
  'zh-HK',
  'zh-TW',
] as const;

// 18.
export const experiences = [
  'No experience',
  '1',
  '2',
  '3',
  '4',
  '5+',
  '10+',
] as const;

// 19.
export const vacancies = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10+',
] as const;

// 20.
export const teamSizes = [
  '1-10',
  '11-50',
  '51-200',
  '201-500',
  '501-1000',
  '1001-5000',
  '5001-10000',
  '10000+',
] as const;

// Type Definitions
export type Role = (typeof roles)[number];
export type MaritalStatus = (typeof maritalStatus)[number];
export type Gender = (typeof genders)[number];
export type Nationality = (typeof nationalities)[number];
export type SalaryPeriod = (typeof salaryPeriods)[number];
export type Qualification = (typeof qualifications)[number];
export type JobTag = (typeof jobTags)[number]['value'];
export type JobLevel = (typeof jobLevels)[number];
export type JobType = (typeof jobTypes)[number];
export type JobBenefit = (typeof jobBenefits)[number];
export type InterviewStatus = (typeof interviewStatuses)[number];
export type ApplicationStatus = (typeof applicationStatus)[number];
export type WorkType = (typeof workTypes)[number];
export type OrganizationType = (typeof organizationTypes)[number];
export type IndustryType = (typeof industries)[number];
export type Locale = (typeof locales)[number];
export type Experience = (typeof experiences)[number];
export type Vacancy = (typeof vacancies)[number];
export type TeamSize = (typeof teamSizes)[number];
